### PR TITLE
Added Manual Morph #28 and Fix #29 #30

### LINKED ISSUE #29: Morphing Tool flickers as YetaWrench when looking at a facade.
**Example Gif:**
morph o tool issue

**Minecraft Version:** 1.10.2
**Mod Version:** Morph-o-Tool-1.0-12.jar
**Ender IO Version:** EnderIO-1.10.2-3.0.1.126_beta.jar

**Issue:**
Morphing Tool flickers as YetaWrench when looking at a facade where no cables are.

### PR DESCRIPTION
**Pull request by MoreThanHidden**
-Added Manual Morph on Shift + Scroll #28 
-Added Server Client Network Message #30

### CODE REVIEW

**Comment by MoreThanHidden** [comment]
Apologies for adding the gradlew.bat (hadn't removed it from the commit), let me know if you need anything changed on this request. It's stable to the extent of my testing but give it a go if you have time.

**Comment by Alex-hawks** [comment]
I'm going to be that guy and say that you should squash your commits

**Comment by MoreThanHidden** [comment]
Damn Squashing with a Merge is annoying, and yes, I'd rather not do it again to fix that typo 😒

**Comment by PapiDimmi** [comment]
How do I morph manually? Shift + scrolling doesn’t do anything.

**Comment by MoreThanHidden** [comment]
Thought I might have messed something up with the squash, but no its still working.
**Sneak + Scroll:**
manualmorph

**Comment by MoreThanHidden** [comment]
Updated to 1.12 with latest AutoRegLib

**Comment by MoreThanHidden** [comment]
@Vazkii if you could check out this PR when you get a chance, let me know if you want any changes or if you don't think it suits.

Compiled Version if that helps:
[Unofficial-Morph-o-Tool-1.2-PR#33.zip](https://github.com/Vazkii/Morph-o-Tool/files/1190155/Unofficial-Morph-o-Tool-1.2-PR.33.zip)

**Comment by Vazkii** [comment]
I'll have a look after I'm back from my break. I don't want to have to support any potential bugs this causes.

**Comment by Segaja** [comment]
Is there any chance to get this merged at some point? I'm a victim of #30 and would love to see that fixed.

**Comment by TheDeviantCrafter** [comment]
I'd also like to see this merged. It would be especially useful for packs that didn't bother to add aliases in the config file. By default, it doesn't work with Buildcraft very well for example.

**Comment by MoreThanHidden** [comment]
@Vazkii have been using my Fork on Enigmatica 2 Expert without issue, if you don't have time to take a look could I release these changes as an unofficial fork?

**Comment by Vazkii** [comment]
Took me way too long to get this merged. Nonetheless it's in now, thank you for the insane patience.

**Pull request merged**
