### PR TITLE
1.15.2 Port

### PR DESCRIPTION
**Pull request by MoreThanHidden**
Updated to 1.15.2, mouse input event is no longer triggering on movement so is currently morphing on click and Manual Morph via Sneak is still working, Could add a Morph Key or move this to another event.

### CODE REVIEW

**Comment by Vazkii** [comment]
what the fuck I literally was just opening my IDE to do this port thank you

**Comment by Vazkii** [comment]
What exactly is broken?

**Comment by MoreThanHidden** [comment]
The auto morph when hovering over a mods block, because the RawMouseEvent event is only getting triggered by a button press.

**Comment by Vazkii** [comment]
Probably could be moved to a client tick event?

**Comment by MoreThanHidden** [comment]
Yeah could be.

**Comment by Vazkii** [comment]
Sweet, I'll look into that then, thank you very much for your work!

**Comment by MoreThanHidden** [comment]
No worries, is a decent starting point.

I added most of the stuff that had potential to break with the Network and Manual Morph PRs, so felt I had an obligation to help out with it 😅

**Pull request merged**
